### ISSUE TITLE
Evaluate alternatives to APISprout

### ISSUE THREAD

**Issue by orviz** [EOSC-synergy/sqaaas-api-spec#19]
Seems not maintained since 2019, alternatives are collected in [openapi.tools](https://openapi.tools). Most demanding feature is supporting `format: uuid` (see [bug](https://github.com/danielgtaylor/apisprout/issues/38))

Wishlist:
- https available
- Validation of the specification
- Docker instantiation

**Comment by orviz** [comment]
Muonsoft https://github.com/muonsoft/openapi-mock

**Comment by scotchneat** [comment]
This is a node solution: https://github.com/stoplightio/prism

**Comment by orviz** [comment]
Thanks, we eventually took prism tool
